name: Clock_Me
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  sqflite: ^2.3.0
  google_fonts: ^6.1.0
  android_alarm_manager_plus: ^3.0.3
  workmanager: ^0.5.2
  font_awesome_flutter: ^10.6.0
  scrollable_positioned_list: ^0.3.8
  awesome_notifications: ^0.8.3
  percent_indicator: ^4.2.3
  wakelock: ^0.6.2
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo Clock Me Circle.png
    - assets/images/Logo Clock Me Rounded.png
    - assets/images/Logo Clock Me Square.png
    - assets/images/Logo Clock Me Transparent.png
